# Generated by Django 5.2.1 on 2025-11-18 13:27

import cloud.circularizacao.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CircularizacaoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=4)),
                ('codigo', models.CharField(max_length=7)),
                ('ordem', models.IntegerField()),
                ('destinatario_nome', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Acesso de Circularização',
                'verbose_name_plural': 'Acessos de Circularização',
                'db_table': 'cloud_circularizacao_acesso',
            },
        ),
        migrations.CreateModel(
            name='CircularizacaoArquivoRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo_original', models.CharField(blank=True, max_length=255)),
                ('extensao_arquivo', models.CharField(blank=True, max_length=10)),
                ('arquivo', models.FileField(upload_to='circularizacao/arquivos_recebidos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_recebidos', to='circularizacao.circularizacaoacesso')),
            ],
            options={
                'verbose_name': 'Arquivo Recebido de Circularização',
                'verbose_name_plural': 'Arquivos Recebidos de Circularização',
                'db_table': 'cloud_circularizacao_arquivo_recebido',
            },
        ),
        migrations.CreateModel(
            name='CircularizacaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(default=cloud.circularizacao.models.CircularizacaoCliente.generate_unique_code, max_length=255, unique=True)),
                ('_senha', models.BinaryField(db_column='senha')),
                ('ano_vigente', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circularizacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente de Circularização',
                'verbose_name_plural': 'Clientes de Circularização',
                'db_table': 'cloud_circularizacao_cliente',
            },
        ),
        migrations.AddField(
            model_name='circularizacaoacesso',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circularizacao_acesso', to='circularizacao.circularizacaocliente'),
        ),
    ]
