"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

from celery.schedules import crontab

API_USERNAME = os.getenv('API_USERNAME')
API_PASSWORD = os.getenv('API_PASSWORD')
DOWNLOAD_AGENDA = os.getenv('DOWNLOAD_AGENDA')
API_URL = os.getenv('API_URL')
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', None)
FERNET_SECRET_KEY = os.getenv('FERNET_SECRET_KEY', None)

DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 't')
SANDBOX_NFE = os.getenv('SANDBOX_NFE', 'False')

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '177.153.20.14',
    'api.allnube.com.br',
    'allnube.com.br',
    'www.allnube.com.br',
]

CURRENT_URL = os.getenv('API_URL')
CURRENT_URL_FRONTEND_PASSWORD_REQUEST = os.getenv('URL_FRONTEND_PASSWORD_REQUEST')
CALLMEBOT_API_KEY = os.getenv('CALLMEBOT_API_KEY')

# ==================== CORS & CSRF CONFIGURATION ====================

if DEBUG:
    # Em desenvolvimento, permitir apenas origens conhecidas
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://127.0.0.1:5500",
    ]
    CORS_ALLOW_CREDENTIALS = True  # Permitir credenciais em desenvolvimento

    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://127.0.0.1:5500",
    ]
else:
    # Em produção, permitir apenas origens específicas
    CORS_ALLOWED_ORIGINS = [
        "https://api.allnube.com.br",

        "https://allnube.com.br",
        "https://www.allnube.com.br",

        "https://agendagrupo.azevedo.cnt.br",
        "https://www.agendagrupo.azevedo.cnt.br",

        "https://leads.azv.tec.br",
        "https://www.leads.azv.tec.br",

        "https://dbresumof.numb3rs.com.br",
        "https://www.dbresumof.numb3rs.com.br",

        'https://gov.numb3rs.com.br',
        'https://www.gov.numb3rs.com.br',

        'https://moneyupgestao.com.br',
        'https://www.moneyupgestao.com.br',
    ]
    CORS_ALLOW_CREDENTIALS = True  # Permitir credenciais (por exemplo, cookies ou JWTs)

    CSRF_TRUSTED_ORIGINS = [
        "https://api.allnube.com.br",

        "https://allnube.com.br",
        "https://www.allnube.com.br",

        'https://agendagrupo.azevedo.cnt.br',
        'https://www.agendagrupo.azevedo.cnt.br',

        "https://leads.azv.tec.br",
        "https://www.leads.azv.tec.br",

        "https://dbresumof.numb3rs.com.br",
        "https://www.dbresumof.numb3rs.com.br",

        'https://gov.numb3rs.com.br',
        'https://www.gov.numb3rs.com.br',

        'https://moneyupgestao.com.br',
        'https://www.moneyupgestao.com.br',
    ]

# Cabeçalhos permitidos para CORS
CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
    'x-requested-with',
    'x-csrftoken',
    'accept',
    'origin',
    'user-agent',
]

# Métodos HTTP permitidos para CORS
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

# ==================== SECURITY SETTINGS (PRODUÇÃO) ====================

if not DEBUG:
    SECURE_SSL_REDIRECT = True  # Redirecionar para HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Para quando estiver atrás de proxy
    SESSION_COOKIE_SECURE = True  # Certifique-se de que os cookies são seguros (HTTPS)
    CSRF_COOKIE_SECURE = True  # CSRF também requer HTTPS
    SECURE_BROWSER_XSS_FILTER = True  # Protege contra ataques de XSS
    SECURE_CONTENT_TYPE_NOSNIFF = True  # Impede sniffing de tipo de conteúdo
    X_FRAME_OPTIONS = 'DENY'  # Evita que a página seja exibida em frames (clickjacking)

# ==================== DJANGO CONFIG ====================

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Utilizando Rest Framework
    'rest_framework',
    # Simplejwt
    'rest_framework_simplejwt',
    # Documentação
    'drf_spectacular',
    # Apps
    'authentication',
    'nfe',
    'nfe_evento',
    'nfe_resumo',
    'empresa',
    'apexcharts',
    'sistema',

    'cloud.circularizacao',
    'cloud.segmento',
    'cloud.cliente',

    # App para controlar migracoes de banco empresas
    'db_allnube_empresa',

    # Leads
    'leads_api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.core.middleware.CurrentUserMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

# ==================== DATABASE ====================

"""
 Quando configurado, direciona automaticamente as queries para o banco correto baseado no modelo sendo acessado.
"""
DATABASE_ROUTERS = []

"""
Permite controle sobre onde as migrações são aplicadas
"""
MIGRATION_MODULES = {
    'db_allnube_empresa': 'db_allnube_empresa.migrations',
}

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_CONNECTION', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_DATABASE', 'allnube_db'),
        'USER': os.getenv('DB_USERNAME', 'allnube_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# ==================== PASSWORD VALIDATORS ====================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==================== LOGS ====================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/error.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

# ==================== I18N ====================

LANGUAGE_CODE = 'pt-BR'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# ==================== STATIC & MEDIA FILES ====================

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# ==================== FILE UPLOAD LIMIT ====================

DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB

# ==================== EMAIL BALANÇO ===========================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_BALANCO_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_BALANCO_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_BALANCO_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_BALANCO_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_BALANCO_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_BALANCO_FROM_EMAIL', '')

# ==================== EMAIL NUMB3RS ===========================
EMAIL_NUMB3RS_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_NUMB3RS_HOST = os.getenv('EMAIL_NUMB3RS_HOST', 'smtp.gmail.com')
EMAIL_NUMB3RS_PORT = int(os.getenv('EMAIL_NUMB3RS_PORT', 587))
EMAIL_NUMB3RS_USE_TLS = os.getenv('EMAIL_NUMB3RS_USE_TLS', 'True').lower() == 'true'
EMAIL_NUMB3RS_HOST_USER = os.getenv('EMAIL_NUMB3RS_HOST_USER', '')
EMAIL_NUMB3RS_HOST_PASSWORD = os.getenv('EMAIL_NUMB3RS_HOST_PASSWORD', '')
DEFAULT_NUMB3RS_FROM_EMAIL = os.getenv('DEFAULT_NUMB3RS_FROM_EMAIL', '')

# ==================== DJANGO REST FRAMEWORK ====================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ==================== JWT SETTINGS ====================

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=2),
}

# ==================== CUSTOM SETTINGS ====================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
APP_VERSION = '1.0.0'
MAX_FILE_UPLOAD_SIZE = 104857600  # 100MB

SPECTACULAR_SETTINGS = {
    'TITLE': 'Azevedo sistemas',
    'DESCRIPTION': 'Documentação dos sistemas da azevedo',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # Determina como as operações devem ser classificadas. Se você pretende fazer a classificação com um
    # PREPROCESSING_HOOKS, certifique-se de desabilitar esta configuração. Se configurado, a classificação
    # é aplicada após o PREPROCESSING_HOOKS. Aceita
    # True (alpha-sorter do drf-spectacular), False ou um valor invocável para o argumento-chave de classificação.
    'SORT_OPERATIONS': False,  # Ordenar automaticamente

    # Determina se os parâmetros da operação devem ser classificados alfanumericamente ou apenas
    # na ordem em que chegaram. Aceita Verdadeiro, Falso ou um valor invocável para o argumento-chave da classificação.
    'SORT_OPERATION_PARAMETERS': False,

    'COMPONENT_SPLIT_REQUEST': True,

    'COMPONENT_SECURITY_SCHEMES': {
        'bearerAuth': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
        },
    },

    'PREPROCESSING_HOOKS': [
        'app.schema_hooks.remove_specific_paths',
    ],
}

# Configurações S3
AWS_USE_S3_UPLOAD = os.getenv('AWS_USE_S3_UPLOAD', 'False').lower() == 'true'
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
AWS_DEFAULT_REGION = os.getenv('AWS_DEFAULT_REGION', 'us-east-1')
AWS_BUCKET = os.getenv('AWS_BUCKET', '')

# Storage padrão
DEFAULT_FILE_STORAGE = 'app.storage_backends.conditional_storage'

# ==================== CELERY CONFIGURATION ====================
# Redis Configuration (via Docker)
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
REDIS_DB = os.environ.get('REDIS_DB', '0')

# Broker URLs - USANDO REDIS
CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'

# Serialization
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Timezone
CELERY_TIMEZONE = TIME_ZONE

# Task tracking
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_RESULT_EXPIRES = 3600  # 1 hour

# Connection settings
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 10

# For development - set to False to use Redis, True for eager mode
CELERY_TASK_ALWAYS_EAGER = False

# Worker settings
CELERY_WORKER_CONCURRENCY = 4
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100

# Logging
CELERY_WORKER_HIJACK_ROOT_LOGGER = False

# Configuração do Celery Beat (tarefas agendadas)
CELERY_BEAT_SCHEDULE = {
    # Automação NFe - Executa de 00:00 até 07:00 a cada 30 minutos
    'automatizar-nfe': {
        'task': 'nfe.tasks.automatizar_nfe',
        'schedule': crontab(hour='0-7', minute='*/30'),  # 00:00, 00:30, 01:00, ..., 07:00
        'options': {
            'expires': 1800,  # Expira após 30 minutos
        }
    },

    # Executar também em horário comercial (se necessário)
    # 'automatizar-nfe-comercial': {
    #     'task': 'nfe.tasks.automatizar_nfe',
    #     'schedule': crontab(hour='8-18', minute='*/60'),  # A cada hora
    #     'options': {
    #         'expires': 3600,
    #     }
    # },
}

# Lock timeout para evitar execução simultânea
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 25  # 25 minutos
CELERY_TASK_TIME_LIMIT = 60 * 30  # 30 minutos
