# Generated by Django 5.2.1 on 2025-10-03 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('cargo', models.CharField(blank=True, choices=[('DIR', 'Diretor'), ('GER', 'Gerente'), ('SUP', 'Supervisor'), ('COORD', 'Coordenador'), ('ASS', 'Assistente'), ('AUX', 'Auxiliar'), ('ADM', 'Administrador'), ('ANL', 'Analista'), ('ENG', 'Engenheiro'), ('TEC', 'Técnico'), ('EST', 'Estagiário'), ('CONS', 'Consultor'), ('DEV', 'Desenvolvedor'), ('PROF', 'Professor'), ('MED', 'Médico'), ('ENF', 'Enfermeiro'), ('ADV', 'Advogado'), ('JUR', 'Jurídico'), ('PSI', 'Psicólogo'), ('VEND', 'Vendedor'), ('REP', 'Representante'), ('MKT', 'Marketing'), ('RH', 'Recursos Humanos'), ('FIN', 'Financeiro'), ('CONT', 'Contador'), ('TI', 'TI - Tecnologia da Informação'), ('OPR', 'Operador'), ('MEC', 'Mecânico'), ('MOT', 'Motorista'), ('ZEL', 'Zelador'), ('SEG', 'Segurança'), ('LIM', 'Serviços Gerais / Limpeza'), ('RECP', 'Recepcionista'), ('ATD', 'Atendente')], max_length=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='empresa.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='sistema.sistema')),
                ('usuario_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas', to='acesso.usuarioempresa')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPermissaoRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitido', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='sistema.gruporotasistema')),
                ('rota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='sistema.rotasistema')),
                ('usuario_sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_rotas', to='acesso.usuariosistema')),
            ],
            options={
                'unique_together': {('usuario_sistema', 'grupo'), ('usuario_sistema', 'rota')},
            },
        ),
    ]
