# Generated by Django 5.2.1 on 2025-10-03 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RotaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
                ('metodo', models.CharField(default='GET', max_length=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='sistema.sistema')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoRotaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_rotas', to=settings.AUTH_USER_MODEL)),
                ('rotas', models.ManyToManyField(related_name='grupos', to='sistema.rotasistema')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_rotas', to='sistema.sistema')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas', to='empresa.empresa')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='sistema.sistema')),
            ],
            options={
                'unique_together': {('empresa', 'sistema')},
            },
        ),
    ]
