# Generated by Django 5.2.1 on 2025-10-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresasistema',
            name='criar_banco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresasistema',
            name='max_funcionarios_registros',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
