# Generated by Django 5.2.1 on 2025-09-09 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoNFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_nfe', models.CharField(max_length=44, verbose_name='Chave da NFe')),
                ('tipo_documento', models.CharField(choices=[('resNFe', 'Resumo NFe'), ('resEvento', 'Resumo Evento')], max_length=10, verbose_name='Tipo de Documento')),
                ('cnpj_emitente', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ')),
                ('nome_emitente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=14, null=True, verbose_name='Inscrição Estadual')),
                ('data_emissao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('tipo_nf', models.PositiveIntegerField(blank=True, choices=[(0, 'Entrada'), (1, 'Saída')], null=True, verbose_name='Tipo de NF')),
                ('valor_nf', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor da NF')),
                ('digest_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor do Digest')),
                ('data_recebimento', models.DateTimeField(verbose_name='Data de Recebimento')),
                ('numero_protocolo', models.CharField(max_length=20, verbose_name='Número do Protocolo')),
                ('situacao_nfe', models.PositiveIntegerField(blank=True, choices=[(1, 'Autorizada'), (2, 'Cancelada'), (3, 'Denegada')], null=True, verbose_name='Situação da NFe')),
                ('tipo_evento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de Evento')),
                ('sequencia_evento', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sequência do Evento')),
                ('descricao_evento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição do Evento')),
                ('orgao', models.CharField(blank=True, max_length=2, null=True, verbose_name='Órgão')),
                ('file_xml', models.FileField(upload_to='xml/resumos/', verbose_name='Arquivo XML')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumos_nfe', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Resumo NFe',
                'verbose_name_plural': 'Resumos NFe',
                'unique_together': {('chave_nfe', 'tipo_documento')},
            },
        ),
    ]
