# Generated by Django 5.2.1 on 2025-08-30 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoNFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_nfe', models.CharField(max_length=44, unique=True, verbose_name='Chave da NFe')),
                ('cnpj_emitente', models.CharField(max_length=14, verbose_name='CNPJ Emitente')),
                ('nome_emitente', models.CharField(max_length=100, verbose_name='Nome do Emitente')),
                ('inscricao_estadual', models.CharField(max_length=14, verbose_name='Inscrição Estadual')),
                ('data_emissao', models.DateTimeField(verbose_name='Data de Emissão')),
                ('tipo_nf', models.PositiveIntegerField(choices=[(0, 'Entrada'), (1, 'Saída')], verbose_name='Tipo de NF')),
                ('valor_nf', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da NF')),
                ('digest_value', models.CharField(max_length=100, verbose_name='Valor do Digest')),
                ('data_recebimento', models.DateTimeField(verbose_name='Data de Recebimento')),
                ('numero_protocolo', models.CharField(max_length=15, verbose_name='Número do Protocolo')),
                ('situacao_nfe', models.PositiveIntegerField(choices=[(1, 'Autorizada'), (2, 'Cancelada'), (3, 'Denegada')], verbose_name='Situação da NFe')),
                ('file_xml', models.FileField(upload_to='xml/resumos/', verbose_name='Arquivo XML')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumos_nfe', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Resumo NFe',
                'verbose_name_plural': 'Resumos NFe',
            },
        ),
    ]
