# Generated by Django 5.2.1 on 2025-10-27 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0007_conexaobanco_status'),
        ('segmento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], default='1', max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('pasta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpastas', to='cliente.pasta')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas_do_segmento', to='segmento.segmento')),
            ],
            options={
                'verbose_name': 'Pasta',
                'verbose_name_plural': 'Pastas',
                'db_table': 'cloud_pasta',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], default='1', max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_do_usuario', to='empresa.empresa')),
                ('segmentos', models.ManyToManyField(related_name='clientes_do_segmento', to='segmento.segmento')),
                ('pastas', models.ManyToManyField(related_name='clientes_da_pasta', to='cliente.pasta')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cloud_cliente',
            },
        ),
        migrations.CreateModel(
            name='AdministradorPasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_designacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_pastas', to='empresa.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas_administradas', to=settings.AUTH_USER_MODEL)),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores_da_pasta', to='cliente.pasta')),
            ],
            options={
                'verbose_name': 'Administrador de Pasta',
                'verbose_name_plural': 'Administradores de Pastas',
                'db_table': 'cloud_clientes_administrador_pasta',
                'unique_together': {('pasta', 'funcionario')},
            },
        ),
    ]
