# Generated by Django 5.2.1 on 2025-11-27 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('empresa', '0007_conexaobanco_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastaFixada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('fixado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas_fixadas', to='empresa.empresa')),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixada_por_usuarios', to='cliente.pasta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas_fixadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pasta Fixada',
                'verbose_name_plural': 'Pastas Fixadas',
                'db_table': 'cloud_pasta_fixada',
                'ordering': ['ordem', '-fixado_em'],
                'unique_together': {('usuario', 'pasta')},
            },
        ),
        migrations.CreateModel(
            name='PastaRecente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acessado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas_recentes', to='empresa.empresa')),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessada_recentemente', to='cliente.pasta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas_recentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pasta Recente',
                'verbose_name_plural': 'Pastas Recentes',
                'db_table': 'cloud_pasta_recente',
                'ordering': ['-acessado_em'],
                'unique_together': {('usuario', 'pasta')},
            },
        ),
    ]
