# Generated by Django 5.2.1 on 2025-10-28 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('empresa', '0007_conexaobanco_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_original', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='arquivos/%Y/%m/%d/')),
                ('tipo', models.CharField(choices=[('1', 'Documento'), ('2', 'Planilha'), ('3', 'Imagem'), ('4', 'PDF'), ('5', 'Outro')], default='5', max_length=1)),
                ('extensao', models.CharField(max_length=10)),
                ('tamanho', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], default='1', max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_da_empresa', to='empresa.empresa')),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_da_pasta', to='cliente.pasta')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'db_table': 'cloud_arquivo',
                'indexes': [models.Index(fields=['pasta', 'status'], name='cloud_arqui_pasta_i_a0411e_idx'), models.Index(fields=['empresa', 'criado_em'], name='cloud_arqui_empresa_640cbc_idx')],
            },
        ),
    ]
