# Generated by Django 5.2.1 on 2025-11-29 18:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_pastafixada_pastarecente'),
        ('empresa', '0007_conexaobanco_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='administradorpasta',
            unique_together={('pasta', 'funcionario', 'empresa')},
        ),
    ]
