# Generated by Django 5.2.1 on 2025-12-03 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_administradorpasta_unique_together'),
        ('empresa', '0007_conexaobanco_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastarecente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastas_recentes', to='empresa.empresa'),
        ),
    ]
