# Generated by Django 5.2.1 on 2025-12-03 17:40

import app.utils.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_pastarecente_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(storage=app.utils.storage_backends.S3Storage(), upload_to='arquivos/%Y/%m/%d/'),
        ),
    ]
