# Generated by Django 5.2.1 on 2025-12-05 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_arquivo_arquivo'),
        ('empresa', '0007_conexaobanco_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='drive',
            field=models.CharField(choices=[('1', 'Local'), ('2', 'Amazon S3')], default='1', max_length=1),
        ),
        migrations.AddIndex(
            model_name='arquivo',
            index=models.Index(fields=['drive'], name='cloud_arqui_drive_86a3a8_idx'),
        ),
    ]
