# Generated by Django 5.2.1 on 2025-12-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_arquivo_deletado_por_cliente_deletado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pastas',
        ),
    ]
