# Generated by Django 5.2.1 on 2026-04-09 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0009_alter_funcionario_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da pasta raiz', max_length=255)),
                ('ano', models.IntegerField(help_text='Ano de referência (Obrigatório)')),
                ('validade', models.CharField(choices=[('1_ano', 'Ciclo Anual'), ('mensal', 'Ciclo Mensal')], default='1_ano', max_length=20)),
                ('is_circ', models.BooleanField(default=False, help_text='Indica se é uma raiz gerada via Circularização')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('clientes', models.ManyToManyField(blank=True, related_name='segmentos_vinculados', to='empresa.empresa')),
                ('empresa_auditoria', models.ForeignKey(help_text='Empresa de auditoria proprietária da estrutura', on_delete=django.db.models.deletion.CASCADE, related_name='segmentos_criados', to='empresa.empresa')),
                ('responsaveis', models.ManyToManyField(blank=True, related_name='segmentos_responsaveis', to='empresa.funcionario')),
            ],
            options={
                'verbose_name': 'Segmento',
                'verbose_name_plural': 'Segmentos',
            },
        ),
        migrations.CreateModel(
            name='Circularizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID usado na URL pública', unique=True)),
                ('ano', models.IntegerField(help_text='Ano da circularização (Obrigatório)')),
                ('senha', models.CharField(help_text='Código de segurança para abrir o link (Ex: ABC123)', max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circularizacoes', to='empresa.empresa')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circularizacoes_responsaveis', to='empresa.funcionario')),
                ('segmento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='circularizacao_link', to='azevedo_cloud.segmento')),
            ],
            options={
                'verbose_name': 'Circularização',
                'verbose_name_plural': 'Circularizações',
            },
        ),
        migrations.CreateModel(
            name='Subpasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('categoria_circ', models.CharField(blank=True, help_text='Ex: CCF, CCA, CCB', max_length=50, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpastas', to='azevedo_cloud.segmento')),
            ],
            options={
                'verbose_name': 'Subpasta',
                'verbose_name_plural': 'Subpastas',
            },
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_remetente', models.CharField(help_text='Nome de quem enviou (útil para links externos sem login)', max_length=150)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='azevedo_cloud/arquivos/%Y/%m/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_cliente', to='empresa.empresa')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_enviados', to=settings.AUTH_USER_MODEL)),
                ('subpasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='azevedo_cloud.subpasta')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
        migrations.AddConstraint(
            model_name='segmento',
            constraint=models.UniqueConstraint(condition=models.Q(('is_circ', False)), fields=('empresa_auditoria', 'nome', 'ano'), name='unique_segmento_auditoria_por_ano'),
        ),
        migrations.AddConstraint(
            model_name='circularizacao',
            constraint=models.UniqueConstraint(fields=('cliente', 'ano'), name='unique_circularizacao_por_cliente_ano'),
        ),
    ]
