# Generated by Django 5.2.1 on 2025-10-03 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConexaoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_host', models.BinaryField(db_column='host')),
                ('_porta', models.BinaryField(db_column='porta')),
                ('_usuario', models.BinaryField(db_column='usuario')),
                ('_senha', models.BinaryField(db_column='senha')),
                ('_database', models.BinaryField(db_column='database')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conexao_banco', to='empresa.empresa')),
            ],
        ),
    ]
