# Generated by Django 5.2.1 on 2025-10-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_conexaobanco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ie',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
