# Generated by Django 5.2.1 on 2025-10-05 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_funcionario'),
        ('sistema', '0002_empresasistema_criar_banco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotasPermitidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas_permitidas', to='empresa.funcionario')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas_permitidas', to='sistema.gruporotasistema')),
            ],
        ),
    ]
