# Generated by Django 5.2.1 on 2025-10-07 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_rotaspermitidas'),
        ('sistema', '0002_empresasistema_criar_banco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sistemas', to='sistema.sistema'),
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(condition=models.Q(('matriz_filial__isnull', True)), fields=('usuario', 'sistema'), name='unique_matriz_por_usuario_sistema'),
        ),
    ]
