# Generated by Django 5.2.1 on 2026-04-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_alter_funcionario_empresa_alter_funcionario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('auditor', 'Auditor'), ('administrativo', 'Administrativo'), ('estagiario', 'Estagiário'), ('cliente_externo', 'Cliente Externo')], max_length=20),
        ),
    ]
