# Generated by Django 5.2.1 on 2026-05-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_alter_funcionario_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente'), ('auditor', 'Auditor'), ('administrativo', 'Administrativo'), ('estagiario', 'Estagiário'), ('cliente_externo', 'Cliente Externo'), ('secretaria', 'Secretaria'), ('financeiro', 'Financeiro'), ('auxiliar_geral', 'Auxiliar geral')], max_length=20),
        ),
    ]
