# Generated by Django 5.2.1 on 2025-10-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_allnube_empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalflat',
            name='teste',
            field=models.BooleanField(default=True),
        ),
    ]
