# Generated by Django 5.2.1 on 2026-06-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_allnube_empresa', '0002_increase_address_field_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatarioflat',
            name='xPais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
