# Generated by Django 5.2.1 on 2025-10-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_allnube_empresa', '0002_notafiscalflat_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscalflat',
            name='teste',
        ),
    ]
