# Generated by Django 5.2.1 on 2026-01-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
