# Generated by Django 5.2.1 on 2026-02-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_api', '0002_lead_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=150)),
                ('fantasia', models.CharField(max_length=150)),
                ('cod_nat_jur', models.CharField(max_length=20)),
                ('natureza_juridica', models.CharField(max_length=150)),
                ('cnes', models.CharField(max_length=50)),
                ('cpf_cnpj', models.CharField(max_length=50)),
                ('tipo_unidade', models.CharField(max_length=150)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(blank=True, max_length=100, null=True)),
                ('faturamento_sus_2020', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('qtde_leitos', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cnes',
            },
        ),
    ]
