# Generated by Django 5.2.1 on 2026-02-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_api', '0003_cnes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cnes',
            index=models.Index(fields=['cidade'], name='cnes_cidade_ed18a2_idx'),
        ),
        migrations.AddIndex(
            model_name='cnes',
            index=models.Index(fields=['uf'], name='cnes_uf_9efb47_idx'),
        ),
        migrations.AddIndex(
            model_name='cnes',
            index=models.Index(fields=['cnes'], name='cnes_cnes_90984a_idx'),
        ),
        migrations.AddIndex(
            model_name='cnes',
            index=models.Index(fields=['cpf_cnpj'], name='cnes_cpf_cnp_bc887f_idx'),
        ),
    ]
