# Generated by Django 5.2.1 on 2026-03-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_api', '0005_lead_apelido_lead_cod_nat_jur_lead_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_extra',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
