# Generated by Django 5.2.1 on 2026-03-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_api', '0007_contact_created_by_contact_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_municip', models.CharField(max_length=50, unique=True)),
                ('ds_nome', models.CharField(max_length=200)),
                ('ds_nomepad', models.CharField(max_length=200)),
                ('co_uf', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'municipalities',
            },
        ),
    ]
