# Generated by Django 5.2.1 on 2026-03-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_api', '0008_municipalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações gerais sobre o lead', null=True),
        ),
    ]
