# Generated by Django 5.2.1 on 2026-04-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_api', '0009_lead_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
