# Generated by Django 5.2.1 on 2026-04-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_api', '0010_add_telefone_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='celular',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='setor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='cnes',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='cnpj',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
